### ISSUE TITLE
大佬搞个deb直接安装

### ISSUE THREAD

**Issue by sikenali** [SeptemberHX/dde-pstate#2]

**Comment by sikenali** [comment]
jingle@jingle:~$ cd dde-pstate-0.0.1/
jingle@jingle:~/dde-pstate-0.0.1$ chmod +x ./install.sh
jingle@jingle:~/dde-pstate-0.0.1$ ./install.sh 
install: 无法创建普通文件'/home/jingle/.local/lib/dde-dock/plugins/libdde_pstate.so': 没有那个文件或目录
[sudo] jingle 的密码：
install: 无法创建普通文件'/opt/dde-dock/scripts/set_prefs.sh': 没有那个文件或目录

**Comment by SeptemberHX** [comment]
我学一下deb怎么打包.

安装脚本看来有问题，我以为 install 会自动创建对应目录来着.。。。
```
sudo mkdir -p /opt/dde-dock/scripts
mkdir -p ~/.local/lib/dde-dock/plugins
```
先创建两个目录就好了

**Comment by SeptemberHX** [comment]
已更新deb包
