### ISSUE TITLE
How run?

### ISSUE THREAD

**Issue by xerenahmed** [SeptemberHX/dde-pstate#8]
I installed but i don't know how run

**Comment by SeptemberHX** [comment]
A new icon should be shown in the plugin area of dock. Just click it.

**Comment by xerenahmed** [comment]
I rebooted and it came. But something seems wrong
![image](https://user-images.githubusercontent.com/35738714/91969362-a6b67a80-ed1e-11ea-9159-0ee9a39b7bec.png)
only have cpu

**Comment by SeptemberHX** [comment]
Could you please post the output of `ls /sys/devices/system/cpu/cpu0/cpufreq/` ?
This tool depends on the files in this directory.
If there is nothing in it or the directory doesn't exist, please install `cpufrequtils` and try again

**Comment by xerenahmed** [comment]
![image](https://user-images.githubusercontent.com/35738714/92306049-0cac3780-ef95-11ea-943a-66f1f53cd353.png)

**Comment by SeptemberHX** [comment]
Please post the output of `cat /sys/devices/system/cpu/cpu0/scaling_governor`

If you have the right drivers installed, the file should contain items like `performance`, `powersave`, etc.

And please also post the output of `sudo /opt/dde-dock/scripts/set_prefs.sh -read-all`.

**Comment by xerenahmed** [comment]
```
eren@eren-PC:~$ cat /sys/devices/system/cpu/cpu0/scaling_governor
cat: /sys/devices/system/cpu/cpu0/scaling_governor: Böyle bir dosya ya da dizin yok
eren@eren-PC:~$ sudo /opt/dde-dock/scripts/set_prefs.sh -read-all
Parola
[sudo] password for eren: 
Doğrulama başarılı
cat: /sys/devices/system/cpu/intel_pstate/min_perf_pct: Böyle bir dosya ya da dizin yok
cat: /sys/devices/system/cpu/intel_pstate/max_perf_pct: Böyle bir dosya ya da dizin yok
cat: /sys/devices/system/cpu/intel_pstate/no_turbo: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_min_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_max_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_RP1_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_RP0_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_boost_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/class/drm/card0/gt_cur_freq_mhz: Böyle bir dosya ya da dizin yok
cat: /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference: Böyle bir dosya ya da dizin yok
cat: /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences: Böyle bir dosya ya da dizin yok
{"cpu_min_perf":"","cpu_max_perf":"","cpu_turbo":"true","gpu_min_freq":"","gpu_max_freq":"","gpu_min_limit":"","gpu_max_limit":"","gpu_boost_freq":"","gpu_cur_freq":"","cpu_governor":"ondemand","energy_perf":"","available_gov":["conservative","ondemand","userspace","powersave","performance","schedutil"],"available_energy":]}
```
"Böyle bir dosya yada dizin yok" = No such file or directory

**Comment by SeptemberHX** [comment]
Seems the script failed to fetch the `/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences`, and return the data as json string without a `[` : `"available_energy":]`

Which version do you use ? I tested the code and `"available_energy":[]` was returned when energy_performance_available_preferences was missing.
